export const TEMPLATE_FIXTURE_VALUES = Object.freeze({
  review_id: 'review-01',
  mode_banner: 'Mode: `normal`',
  artifact_absolute: '/repo/docs/example.md',
  workspace_absolute: '/repo/.scratch/peer-review/review-01',
  response_absolute: '/repo/docs/peer-reviews/spec/example/reviewer-response-1.md',
  invitation_absolute: '/repo/docs/peer-reviews/spec/example/reviewer-invitation.md',
  artifact_display: '`/repo/docs/example.md`',
  workspace_display: '`/repo/.scratch/peer-review/review-01`',
  response_display: '`/repo/docs/peer-reviews/spec/example/reviewer-response-1.md`',
  invitation_display: '`/repo/docs/peer-reviews/spec/example/reviewer-invitation.md`',
  invitation_payload: 'cGF5bG9hZA',
  installed_join_display:
    '`peer-review join /repo/docs/peer-reviews/spec/example/reviewer-invitation.md`',
  zero_install_join_display:
    '`npx --yes @kburson/ai-peer-review@0.2.2 join /repo/docs/peer-reviews/spec/example/reviewer-invitation.md`',
  recovery_display: '`peer-review resume /repo/.scratch/peer-review/review-01`',
  reviewer_selection_display: 'Claude Opus 5 (claude-opus-5), effort: medium',
  runtime_display: 'XPR, project-local broker',
  broker_reconcile_display:
    '`peer-review broker reconcile /repo/.scratch/peer-review/review-01 --json`',
  status_next_display: '`peer-review status /repo/.scratch/peer-review/review-01 --next`',
  frontmatter: '---\nschema: "ai-peer-review.response/v1"\n---',
  summary: 'Summary text.',
  findings: 'None.',
  required_changes: 'None.',
  optional_suggestions: 'None.',
  decision: 'accepted',
  finding_dispositions: 'None.',
  changes_made: 'No changes.',
  declined_changes: 'None.',
  verification: 'Tests passed.',
  human_rationale: 'Accepted with documented rationale.',
  manifest_body: 'Manifest evidence.',
});
